"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-14 13:27:48.540957
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('terms_url', sa.Text(), nullable=True),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('daily_call_budget', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('province_code', sa.String(length=2), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('altitude_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('moderation_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("moderation_status IN ('active','excluded','review')", name='station_moderation'),
    sa.CheckConstraint("province_code IN ('05','19','28','40') OR province_code IS NULL", name='station_province'),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90 OR latitude IS NULL', name='station_latitude'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180 OR longitude IS NULL', name='station_longitude'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_location_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('altitude_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='location_window'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_location_history_station_id'), 'station_location_history', ['station_id'], unique=False)
    op.create_table('station_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("status IN ('enabled','paused','unavailable')", name='source_status'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'external_id', name='uq_source_provider_external')
    )
    op.create_index(op.f('ix_station_sources_provider_id'), 'station_sources', ['provider_id'], unique=False)
    op.create_index(op.f('ix_station_sources_station_id'), 'station_sources', ['station_id'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_basis', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('coverage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('period_end > period_start', name='daily_summary_window'),
    sa.ForeignKeyConstraint(['source_id'], ['station_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'product', 'period_start', 'period_end', 'period_basis', 'method', name='uq_daily_summary')
    )
    op.create_index(op.f('ix_daily_summaries_source_id'), 'daily_summaries', ['source_id'], unique=False)
    op.create_table('exclusions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('(station_id IS NOT NULL AND source_id IS NULL) OR (station_id IS NULL AND source_id IS NOT NULL)', name='exclusion_one_target'),
    sa.ForeignKeyConstraint(['actor_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['station_sources.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_source_exclusion', 'exclusions', ['source_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('uq_active_station_exclusion', 'exclusions', ['station_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('hourly_aggregates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('minimum', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('maximum', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('mean', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('method', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['station_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'metric', 'period_start', name='uq_hourly_aggregate')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['station_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_basis', sa.String(length=100), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('normalizer_version', sa.String(length=40), nullable=False),
    sa.Column('revised_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(period_start IS NULL AND period_end IS NULL AND period_basis IS NULL) OR (period_start IS NOT NULL AND period_end IS NOT NULL AND period_basis IS NOT NULL AND period_end > period_start)', name='observation_period_pair'),
    sa.ForeignKeyConstraint(['source_id'], ['station_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'product', 'observed_at', 'period_start', 'period_end', 'period_basis', name='uq_observation_semantic', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_observations_source_id'), 'observations', ['source_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('latest_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['station_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'metric', name='uq_latest_source_metric')
    )
    op.create_table('observation_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('previous_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_quality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_payload_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_revisions_observation_id'), 'observation_revisions', ['observation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observation_revisions_observation_id'), table_name='observation_revisions')
    op.drop_table('observation_revisions')
    op.drop_table('latest_observations')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_observations_source_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations')
    op.drop_table('observations')
    op.drop_table('jobs')
    op.drop_table('hourly_aggregates')
    op.drop_index('uq_active_station_exclusion', table_name='exclusions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('uq_active_source_exclusion', table_name='exclusions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('exclusions')
    op.drop_index(op.f('ix_daily_summaries_source_id'), table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_station_sources_station_id'), table_name='station_sources')
    op.drop_index(op.f('ix_station_sources_provider_id'), table_name='station_sources')
    op.drop_table('station_sources')
    op.drop_index(op.f('ix_station_location_history_station_id'), table_name='station_location_history')
    op.drop_table('station_location_history')
    op.drop_table('audit_events')
    op.drop_table('admin_sessions')
    op.drop_table('stations')
    op.drop_table('providers')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
