"""persistent AEMET worker

Revision ID: 0002_aemet_worker
Revises: 0001_initial
Create Date: 2026-09-16 09:41:37.716484
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002_aemet_worker"
down_revision: Union[str, Sequence[str], None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_metadata",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("product", sa.String(length=100), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "product", "payload_hash", name="uq_product_metadata"),
    )
    op.create_table(
        "provider_runtime",
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("day_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("day_calls", sa.Integer(), nullable=False),
        sa.Column("recent_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("blocked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pause_reason", sa.String(length=100), nullable=True),
        sa.Column("last_polled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_new_data_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("newest_observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("provider_id"),
    )
    op.add_column("ingestion_runs", sa.Column("owner_token", sa.Uuid(), nullable=True))
    op.add_column("jobs", sa.Column("dedupe_key", sa.String(length=160), nullable=True))
    op.add_column("jobs", sa.Column("owner_token", sa.Uuid(), nullable=True))
    op.add_column("jobs", sa.Column("attempts", sa.Integer(), server_default="0", nullable=False))
    op.add_column("jobs", sa.Column("priority", sa.Integer(), server_default="0", nullable=False))
    op.add_column(
        "jobs", sa.Column("interval_seconds", sa.Integer(), server_default="900", nullable=False)
    )
    op.create_index("ix_jobs_due", "jobs", ["status", "next_run_at"], unique=False)
    op.create_unique_constraint("jobs_dedupe_key_key", "jobs", ["dedupe_key"])
    # Exclusion INSERTs and ingestion serialize on the same station row, even
    # when an administrator writes through SQL before phase 6 exists.
    op.execute("""
        CREATE FUNCTION lock_exclusion_station() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE target uuid;
        BEGIN
          target := NEW.station_id;
          IF target IS NULL THEN
            SELECT station_id INTO target FROM station_sources WHERE id = NEW.source_id;
          END IF;
          PERFORM id FROM stations WHERE id = target FOR UPDATE;
          RETURN NEW;
        END $$;
    """)
    op.execute("""
        CREATE TRIGGER exclusions_station_lock BEFORE INSERT OR UPDATE ON exclusions
        FOR EACH ROW EXECUTE FUNCTION lock_exclusion_station();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER exclusions_station_lock ON exclusions")
    op.execute("DROP FUNCTION lock_exclusion_station()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("jobs_dedupe_key_key", "jobs", type_="unique")
    op.drop_index("ix_jobs_due", table_name="jobs")
    op.drop_column("jobs", "interval_seconds")
    op.drop_column("jobs", "priority")
    op.drop_column("jobs", "attempts")
    op.drop_column("jobs", "owner_token")
    op.drop_column("jobs", "dedupe_key")
    op.drop_column("ingestion_runs", "owner_token")
    op.drop_table("provider_runtime")
    op.drop_table("product_metadata")
    # ### end Alembic commands ###
