"""network discovery and persistent catalog review

Revision ID: 0003_network_catalog
Revises: 0002_aemet_worker
Create Date: 2026-09-16 16:02:39.324017
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0003_network_catalog"
down_revision: Union[str, Sequence[str], None] = "0002_aemet_worker"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_exclusions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_id", "external_id", name="uq_identity_exclusion"),
    )
    op.create_table(
        "duplicate_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("other_source_id", sa.Uuid(), nullable=False),
        sa.Column("distance_m", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("source_id < other_source_id", name="duplicate_pair_order"),
        sa.ForeignKeyConstraint(
            ["other_source_id"],
            ["station_sources.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["station_sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "other_source_id", name="uq_duplicate_pair"),
    )
    op.add_column(
        "station_sources",
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "station_sources",
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "station_sources",
        sa.Column(
            "source_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column(
        "station_sources", sa.Column("review_reason", sa.String(length=100), nullable=True)
    )
    # Existing detections predate this migration; use their actual station creation time.
    op.execute("""UPDATE station_sources s SET first_seen_at = t.created_at,
                  last_seen_at = t.created_at FROM stations t WHERE t.id = s.station_id""")
    op.execute("""
        CREATE FUNCTION lock_identity_exclusion() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE target uuid;
        BEGIN
          PERFORM pg_advisory_xact_lock(hashtextextended(
            NEW.provider_id::text || ':' || NEW.external_id, 0));
          SELECT station_id INTO target FROM station_sources
            WHERE provider_id = NEW.provider_id AND external_id = NEW.external_id;
          IF target IS NOT NULL THEN
            PERFORM id FROM stations WHERE id = target FOR UPDATE;
          END IF;
          RETURN NEW;
        END $$;
    """)
    op.execute("""CREATE TRIGGER identity_exclusions_lock
        BEFORE INSERT OR UPDATE ON identity_exclusions
        FOR EACH ROW EXECUTE FUNCTION lock_identity_exclusion()""")


def downgrade() -> None:
    op.execute("DROP TRIGGER identity_exclusions_lock ON identity_exclusions")
    op.execute("DROP FUNCTION lock_identity_exclusion()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("station_sources", "review_reason")
    op.drop_column("station_sources", "source_metadata")
    op.drop_column("station_sources", "last_seen_at")
    op.drop_column("station_sources", "first_seen_at")
    op.drop_table("duplicate_candidates")
    op.drop_table("identity_exclusions")
    # ### end Alembic commands ###
